var searchModuleIndex = [
"README",
"graph",
];

var searchIndex = [
"Graph[T]",
"bfs",
"cartesian_product",
"clone",
"complement",
"degeneracy",
"degree_list",
"density",
"dfs",
"diameter",
"get_edge",
"girth",
"has_eulerian_path",
"is_acyclic",
"is_bipartite",
"is_complete",
"is_connected",
"is_cycle",
"is_eulerian",
"is_regular",
"is_tree",
"line_graph",
"max_degree",
"min_degree",
"mst",
"num_connected_components",
"num_edges",
"num_nodes",
"num_spanning_trees",
"num_triangles",
"radius",
"to_adjacency_matrix",
"to_graph6",
"total_weight",
"MSTAlgorithm",
"cycle_graph",
"path_graph",
"complete_graph",
"complete_bipartite_graph",
"star_graph",
"wheel_graph",
"Graph.from_adjacency",
"Graph.from_adjacency_matrix",
"Graph.from_graph6",
"Node",
"Edge",
"Graph",
"Graph.create",
"random_graph6",
];

var searchModuleData = [
["A graph package for the v programming language.","index.html"],
["A graph package for the v programming language.","graph.html"],
];

var searchData = [
["graph","","graph.html#Graph[T]","type "],
["graph","Runs a breadth-first search (bfs) on a given node of the graph. It returns a spa","graph.html#Graph[T].bfs","fn (Graph[T])"],
["graph","","graph.html#Graph[T].cartesian_product","fn (Graph[T])"],
["graph","Creates a clone of the graph, changes made in a clone will not affect the origin","graph.html#Graph[T].clone","fn (Graph[T])"],
["graph","Gives the complement of a graph. The list of (references to) nodes is reused, so","graph.html#Graph[T].complement","fn (Graph[T])"],
["graph","Returns the degeneracy the gr. It implements the algorithm described by Matula a","graph.html#Graph[T].degeneracy","fn (Graph[T])"],
["graph","Returns a list of the degrees of the graph, not necessarily ordered.","graph.html#Graph[T].degree_list","fn (Graph[T])"],
["graph","Returns the density of the graph.","graph.html#Graph[T].density","fn (Graph[T])"],
["graph","Runs a depth-first search (dfs) on a given node of the graph. It returns a spann","graph.html#Graph[T].dfs","fn (Graph[T])"],
["graph","Returns the diameter of the graph, this implementation only works for connected ","graph.html#Graph[T].diameter","fn (Graph[T])"],
["graph","","graph.html#Graph[T].get_edge","fn (Graph[T])"],
["graph","Returns the girth of the graph.","graph.html#Graph[T].girth","fn (Graph[T])"],
["graph","Checks whether the graph contains an Eulerian path.","graph.html#Graph[T].has_eulerian_path","fn (Graph[T])"],
["graph","Checks whether the graph is acyclic, i.e. does not contain a cycle. This differs","graph.html#Graph[T].is_acyclic","fn (Graph[T])"],
["graph","Checks whether the graph is bipartite.","graph.html#Graph[T].is_bipartite","fn (Graph[T])"],
["graph","Checks whether the graph is a complete graph.","graph.html#Graph[T].is_complete","fn (Graph[T])"],
["graph","Checks whether the graph is connected.","graph.html#Graph[T].is_connected","fn (Graph[T])"],
["graph","Checks whether the graph is a cycle.","graph.html#Graph[T].is_cycle","fn (Graph[T])"],
["graph","Checks whether the graph is Eulerian.","graph.html#Graph[T].is_eulerian","fn (Graph[T])"],
["graph","Checks whether the graph is regular.","graph.html#Graph[T].is_regular","fn (Graph[T])"],
["graph","Checks whether the graph is a tree.","graph.html#Graph[T].is_tree","fn (Graph[T])"],
["graph","Gives the line graph of a graph. The values of the nodes are the weights of the ","graph.html#Graph[T].line_graph","fn (Graph[T])"],
["graph","Returns the maximum degree of the graph.","graph.html#Graph[T].max_degree","fn (Graph[T])"],
["graph","Returns the minimum degree of the graph.","graph.html#Graph[T].min_degree","fn (Graph[T])"],
["graph","Finds the minimum spanning tree of a graph. The possible algorithms are listed i","graph.html#Graph[T].mst","fn (Graph[T])"],
["graph","Returns the number of connected components of the graph.","graph.html#Graph[T].num_connected_components","fn (Graph[T])"],
["graph","Returns the number of edges of a graph, also accessible through `Graph.edges.len","graph.html#Graph[T].num_edges","fn (Graph[T])"],
["graph","Returns the number of nodes of a graph, also accessible through `Graph.nodes.len","graph.html#Graph[T].num_nodes","fn (Graph[T])"],
["graph","Returns the number of spanning trees of the graph.","graph.html#Graph[T].num_spanning_trees","fn (Graph[T])"],
["graph","Returns the number of triangles of the gr.","graph.html#Graph[T].num_triangles","fn (Graph[T])"],
["graph","Returns the radius of the graph, this implementation only works for connected gr","graph.html#Graph[T].radius","fn (Graph[T])"],
["graph","Gives the (symmetric) adjacency matrix of the graph. The order of the rows and c","graph.html#Graph[T].to_adjacency_matrix","fn (Graph[T])"],
["graph","Returns the graph6 format of the given graph.","graph.html#Graph[T].to_graph6","fn (Graph[T])"],
["graph","Returns the total weight of all edges of a graph.","graph.html#Graph[T].total_weight","fn (Graph[T])"],
["graph","","graph.html#MSTAlgorithm","enum "],
["graph","Generates a cycle graph on n nodes. The graph's nodes are integer values from 0 ","graph.html#cycle_graph","fn "],
["graph","Generates a path graph on n nodes. The nodes of the graph are integers, from 0 t","graph.html#path_graph","fn "],
["graph","Generates a complete graph on n nodes. The nodes of the graph are integers, from","graph.html#complete_graph","fn "],
["graph","Generates a complete bipartite graph on n x m nodes, with respectively n and m n","graph.html#complete_bipartite_graph","fn "],
["graph","Generates a star graph on n nodes. In this case a star graph on n nodes has n-1 ","graph.html#star_graph","fn "],
["graph","Generates a wheel graph on n nodes. In this case a wheel graph on n nodes has n-","graph.html#wheel_graph","fn "],
["graph","Generates a graph from a mapping with the following signature: `map[T][]T`, with","graph.html#Graph.from_adjacency","fn "],
["graph","Generate a graph from an integer matrix, returns a graph with integer values for","graph.html#Graph.from_adjacency_matrix","fn "],
["graph","Generates a graph from a graph6 string, any invalid string will panic. For more ","graph.html#Graph.from_graph6","fn "],
["graph","A node that contains a value of type `T` in the mutable field`val`. Nodes are st","graph.html#Node","struct "],
["graph","An edge contains two references to nodes of type `T` and an integer weight.","graph.html#Edge","struct "],
["graph","A graph is a list of references to nodes and a list of references to edges made ","graph.html#Graph","struct "],
["graph","Factory function to create an Graph from a list of nodes and a list of edges con","graph.html#Graph.create","fn "],
["graph","Returns a random graph6 string for a graph on `n` nodes, with a given edge proba","graph.html#random_graph6","fn "],
];

