name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install V (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          git clone https://github.com/vlang/v.git /tmp/vlang
          cd /tmp/vlang && make && sudo ./v symlink

      - name: Install V (Windows)
        if: runner.os == 'Windows'
        run: |
          git clone https://github.com/vlang/v.git $env:TEMP\vlang
          cd $env:TEMP\vlang
          .\make.bat
          echo "$env:TEMP\vlang" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Run your project tests
        run: v test .
